language: scala

scala:
- 2.11.2
- 2.10.4

jdk:
- oraclejdk7

script: sbt ++${TRAVIS_SCALA_VERSION} jove-meta/pack jove-scala-cli/pack jove-spark-cli-11-bootstrap/pack jove-spark-cli-12-bootstrap/pack jove-spark-cli-13-bootstrap/pack

sudo: false

